### ISSUE TITLE
[ERROR] TypeError r.init is not a function on Node v16.14.2 on stackblitz.com

### ISSUE THREAD

**Issue by angelhdzmultimedia** [oxilor/nodemon-ts-esm#1]
I use stackblitz.com.

I got a `TypeError r.init is not a function` on Node v16.14.2 (the current version on StackBlitz.

Then created a local project in my PC with VSCode, Node v19.0.0.

No errors.

Then I went and installed Node v16.14.2 in my PC (I use nvm to manage Node executables).

No errors either!

So how can StackBlitz create this error!?

Oh, and this happens with` nodemon src/main.ts` and the `"ts-node": { esm: true }` in `tsconfig.json`, and with `nodemon --exec 'ts-node --esm' src/main.ts`.

(Created yet another project to confirm)
https://stackblitz.com/edit/node-vqh7ml

**Comment by oxilor** [comment]
I imported this repo into stackblitz and I got the same error. I think this error related to the stackblitz, because it works locally.

**Comment by angelhdzmultimedia** [comment]
Ok I'll open an issue there. Thanks mate!
